export type PresentationArchitecture = "art_anchored" | "art_skinned_dynamic" | "environment" | "hybrid" | "utility";
export type ScreenScrollPolicy = "none" | "region_only" | "page";

export interface ScreenArchitectureDefinition {
  screenId: string;
  purpose: string;
  architecture: PresentationArchitecture;
  approvedReference?: string;
  runtimeArtRequired: string[];
  dynamicRegions: string[];
  scrollPolicy: ScreenScrollPolicy;
  logicalDesignSize: { width: number; height: number };
  status: "production" | "provisional" | "development";
  migrationPriority: "gold_standard" | "high" | "medium" | "low" | "none";
  geometryOwners?: Record<string, "art" | "code">;
  artBlocker?: { asset: string; dimensions: string; purpose: string; reference: string };
}

const MAIN = { width: 1428, height: 844 };
const FULL = { width: 1600, height: 900 };

export const SCREEN_ARCHITECTURE: ScreenArchitectureDefinition[] = [
  { screenId:"main_menu", purpose:"Campaign entry", architecture:"art_skinned_dynamic", runtimeArtRequired:["ui kit"], dynamicRegions:["save actions","settings"], scrollPolicy:"none", logicalDesignSize:FULL, status:"development", migrationPriority:"medium" },
  { screenId:"character_creator", purpose:"Create a captain", architecture:"art_skinned_dynamic", approvedReference:"ui.reference.character_creator", runtimeArtRequired:["portrait content art","character culture frame pack","religion accent pack when applicable"], dynamicRegions:["steps","forms","portrait gallery","identity summary","review summary","build-impact note","attribute icon slots","skill icon slots"], scrollPolicy:"none", logicalDesignSize:FULL, status:"development", migrationPriority:"high", geometryOwners:{"locked structural layout":"code","step rail":"code","form layout":"code","fields":"code","portrait frame":"code","portrait slot":"code","portrait image":"art","portrait frame art":"art","identity summary":"code","attribute icon slots":"code","skill icon slots":"code","future attribute/skill icon art":"art","footer controls":"code","review summary":"code","culture frame attachment geometry":"code","culture frame/material art":"art","religion accent socket geometry":"code","religion accent art":"art"} },
  { screenId:"character_sheet", purpose:"Inspect captain identity, progression, standing and relationships", architecture:"art_skinned_dynamic", runtimeArtRequired:["portrait content art","character culture frame pack","religion accent pack when applicable"], dynamicRegions:["origins","standing & law","local port standing","relationships","accordion summaries","accordion bodies","attributes","skills","attribute icon slots","skill icon slots","specializations","abilities","condition"], scrollPolicy:"region_only", logicalDesignSize:MAIN, status:"development", migrationPriority:"high", geometryOwners:{"locked structural layout":"code","record sections":"code","portrait frame":"code","portrait slot":"code","portrait image":"art","portrait frame art":"art","facts":"code","standing accordion summary":"code","standing accordion body":"code","relationship accordion summary":"code","relationship accordion body":"code","local standing accordion summary":"code","local standing accordion body":"code","standing rows":"code","standing & law rows":"code","local standing rows":"code","relationship rows":"code","attributes":"code","skills":"code","attribute icon slots":"code","skill icon slots":"code","future attribute/skill icon art":"art","controls":"code","culture frame attachment geometry":"code","culture frame/material art":"art","religion accent socket geometry":"code","religion accent art":"art"} },
  { screenId:"inventory_equipment", purpose:"Manage personal inventory and worn equipment", architecture:"hybrid", approvedReference:"ui.character.equipment.male.reference / ui.character.equipment.female.reference", runtimeArtRequired:["ui.character.equipment.male.runtime","ui.character.equipment.female.runtime","ui kit"], dynamicRegions:["stats","equipment icons","inventory grid","item detail","filters"], scrollPolicy:"none", logicalDesignSize:MAIN, status:"production", migrationPriority:"gold_standard", geometryOwners:{"equipment slot frames":"art","equipment hitboxes":"code","equipped item icons":"code","inventory grid":"code","inventory item icons":"code","filters":"code","item detail":"code","character summary values":"code"} },
  { screenId:"crew_roster", purpose:"Inspect ship company and named crew records", architecture:"art_skinned_dynamic", approvedReference:"ui.reference.crew_roster", runtimeArtRequired:["named crew portrait art"], dynamicRegions:["ordinary company summary","collective captain attitude","named crew rows","named crew portraits","named crew relationships","named crew sheets","morale","loyalty","pagination"], scrollPolicy:"none", logicalDesignSize:MAIN, status:"development", migrationPriority:"high", geometryOwners:{"pre-art ledger structure":"code","ledger frame":"code","ordinary company block":"code","columns":"code","crew rows":"code","portrait slots":"code","portrait images":"art","named relationship labels":"code","named crew record sections":"code","pagination":"code","controls":"code","future presentation shell":"code"} },
  { screenId:"ship_management", purpose:"Inspect ship, cargo and refits", architecture:"hybrid", approvedReference:"ui.reference.ship_management", runtimeArtRequired:["ship illustration","ui kit"], dynamicRegions:["ship particulars","status groups","status icon slots","cargo","refits","refit icon slots","actions"], scrollPolicy:"none", logicalDesignSize:MAIN, status:"provisional", migrationPriority:"high", geometryOwners:{"ship illustration":"art","ship frame":"code","ship particulars":"code","status groups":"code","status icon slots":"code","status icon art":"art","cargo grid":"code","refit grid":"code","refit icon slots":"code","refit icon art":"art","action controls":"code"} },
  { screenId:"port_work_shipyard", purpose:"Repair/refit/contracts", architecture:"art_skinned_dynamic", runtimeArtRequired:["ui kit","port environment"], dynamicRegions:["contracts","repair","refit"], scrollPolicy:"region_only", logicalDesignSize:MAIN, status:"provisional", migrationPriority:"medium" },
  { screenId:"cargo", purpose:"Inspect ship cargo", architecture:"art_skinned_dynamic", runtimeArtRequired:["ui kit"], dynamicRegions:["cargo grid","capacity"], scrollPolicy:"none", logicalDesignSize:MAIN, status:"provisional", migrationPriority:"medium" },
  { screenId:"market", purpose:"Trade commodities", architecture:"art_skinned_dynamic", approvedReference:"ui.reference.market.veyrholm", runtimeArtRequired:["ui kit","port environment"], dynamicRegions:["table","rows","pagination","summary"], scrollPolicy:"none", logicalDesignSize:MAIN, status:"production", migrationPriority:"gold_standard", geometryOwners:{"ledger frame":"code","table":"code","rows":"code","columns":"code","trade buttons":"code","pagination":"code","summary panel":"code","environment backdrop":"art"} },
  { screenId:"navigation", purpose:"Plot and execute voyages", architecture:"art_anchored", approvedReference:"ui.navigation.approved_reference", runtimeArtRequired:["map regional art"], dynamicRegions:["grid","route","tokens","markers","selection"], scrollPolicy:"none", logicalDesignSize:MAIN, status:"production", migrationPriority:"none" },
  { screenId:"port", purpose:"Interact with a settlement", architecture:"environment", runtimeArtRequired:["port establishing art","ui kit"], dynamicRegions:["actions","people","state"], scrollPolicy:"region_only", logicalDesignSize:MAIN, status:"production", migrationPriority:"low" },
  { screenId:"npc_dialogue", purpose:"Talk to persistent characters", architecture:"environment", runtimeArtRequired:["location art","portrait frame"], dynamicRegions:["portrait","dialogue","responses"], scrollPolicy:"region_only", logicalDesignSize:MAIN, status:"provisional", migrationPriority:"medium" },
  { screenId:"journal_intelligence", purpose:"Read the captain's accumulated knowledge and chronicle", architecture:"art_skinned_dynamic", approvedReference:"ui.reference.journal", runtimeArtRequired:[], dynamicRegions:["tabs","entries","standing & law records","folio metadata","paging"], scrollPolicy:"none", logicalDesignSize:MAIN, status:"development", migrationPriority:"high", geometryOwners:{"pre-art two-page structure":"code","book/page geometry":"code","tabs":"code","entries":"code","folio metadata":"code","paging":"code","future presentation shell":"code"} },
  { screenId:"naval_combat", purpose:"Resolve ship encounters", architecture:"hybrid", approvedReference:"Alpha 0.6D naval combat hierarchy + legacy naval_encounter_base atmosphere only", runtimeArtRequired:["ui.combat.skeldra_tactical_sea","dynamic ship illustration","ui kit"], dynamicRegions:["ships","range","damage","actions","log"], scrollPolicy:"page", logicalDesignSize:MAIN, status:"production", migrationPriority:"none", geometryOwners:{"tactical sea environment":"art","combat layout":"code","ship panels":"code","ship illustrations":"art","range readout":"code","damage stats":"code","actions":"code","combat log":"code"} },
  { screenId:"personal_combat", purpose:"Resolve person-to-person combat", architecture:"hybrid", runtimeArtRequired:["combat environment","ui kit"], dynamicRegions:["combatants","actions","log"], scrollPolicy:"region_only", logicalDesignSize:MAIN, status:"development", migrationPriority:"medium" },
  { screenId:"boarding", purpose:"Resolve boarding transition/combat", architecture:"hybrid", runtimeArtRequired:["boarding environment","ui kit"], dynamicRegions:["combatants","position","actions"], scrollPolicy:"region_only", logicalDesignSize:MAIN, status:"development", migrationPriority:"medium" },
  { screenId:"history", purpose:"Review historical events", architecture:"art_skinned_dynamic", runtimeArtRequired:["ui kit"], dynamicRegions:["records","filters","paging"], scrollPolicy:"page", logicalDesignSize:MAIN, status:"development", migrationPriority:"low" },
  { screenId:"genealogy_dynasties", purpose:"Review lineages/dynasties", architecture:"hybrid", runtimeArtRequired:["ui kit"], dynamicRegions:["tree","people","records"], scrollPolicy:"region_only", logicalDesignSize:MAIN, status:"development", migrationPriority:"low" },
  { screenId:"codex", purpose:"Read lore records", architecture:"art_skinned_dynamic", runtimeArtRequired:["book/ledger skin","ui kit"], dynamicRegions:["article","index"], scrollPolicy:"page", logicalDesignSize:MAIN, status:"development", migrationPriority:"low" },
  { screenId:"event_popup", purpose:"Present significant events/actions", architecture:"art_skinned_dynamic", runtimeArtRequired:["modal frame","event art"], dynamicRegions:["title","copy","choices"], scrollPolicy:"none", logicalDesignSize:MAIN, status:"provisional", migrationPriority:"medium" },
  { screenId:"settings", purpose:"Adjust game preferences", architecture:"art_skinned_dynamic", runtimeArtRequired:["ui kit"], dynamicRegions:["controls"], scrollPolicy:"none", logicalDesignSize:MAIN, status:"development", migrationPriority:"low" },
  { screenId:"save_load", purpose:"Manage saves", architecture:"art_skinned_dynamic", runtimeArtRequired:["ui kit"], dynamicRegions:["save slots","actions"], scrollPolicy:"none", logicalDesignSize:MAIN, status:"development", migrationPriority:"low" }
];

export const SCREEN_ARCHITECTURE_BY_ID = Object.fromEntries(SCREEN_ARCHITECTURE.map((screen) => [screen.screenId, screen])) as Record<string, ScreenArchitectureDefinition>;
