-- Ebbing Tides Alpha 0.6B — Dynasties, Genealogy, Offices, Reigns & Claims
-- Global political/history population only. This does not make non-Skeldran regions traversable.
begin;
set constraints all deferred;

insert into public.houses (world_scope_id,id,name,culture_id,region_id,founded_precision,founded_year,founded_month,founded_day,founded_hour,founded_end_year,ended_precision,ended_year,ended_month,ended_day,ended_hour,ended_end_year,founder_character_id,parent_house_id,cadet_branch_of_house_id,notes,status,canonical_status,origin)
values
  ('canon','house.vaering','House Vaering','skeldran','skeldra','approximate',225,null,null,null,null,'unknown',null,null,null,null,null,'character.vaer_the_red',null,null,'Skeldran royal house. Vaer the Red is the claimed ancestral founder; the earliest links remain traditional/uncertain while the later royal line is documented.','active','canonical','authored'),
  ('canon','house.marcellan','House Marcellan','asterian','asteria','unknown',null,null,null,null,null,'unknown',null,null,null,null,null,null,null,null,'Asterra republican oligarchic family. Aeson Marcellan is a League-era ancestor/political myth, but family prestige does not create a hereditary right to the First Archonship.','active','canonical','authored'),
  ('canon','house.valerian','House Valerian','asterian','asteria','unknown',null,null,null,null,null,'unknown',null,null,null,null,null,null,null,null,'Aurellian imperial dynasty with multiple historical imperial and cadet branches; Solvar Valerian I is a celebrated early ancestor rather than a proven founder record.','active','canonical','authored'),
  ('canon','house.asharan','House Asharan','serathi','serath','year',508,null,null,null,null,'unknown',null,null,null,null,null,'character.ashar_i_asharan',null,null,'Dynasty styled Asharan after Ashar I''s Covenant conversion and kingship; current legitimacy is deeply tied to Covenant history.','active','canonical','authored'),
  ('canon','house.tenrai','House Tenrai','kaishin','kaishin','unknown',null,null,null,null,null,'unknown',null,null,null,null,null,null,null,null,'Long-lived Kaishin imperial house. Tenrai Shun is a centralizing reform ancestor; current canon does not identify him as the literal founder.','active','canonical','authored'),
  ('canon','house.darcon','House Darcon','vesperan','crossroads','unknown',null,null,null,null,null,'unknown',null,null,null,null,null,null,null,null,'Vesperan imperial house whose survival depends on dynastic continuity, religious balancing, court politics, fortification, tolls, and diplomacy rather than simple inheritance alone.','active','canonical','authored')
on conflict (world_scope_id,id) do update set
  name=excluded.name, culture_id=excluded.culture_id, region_id=excluded.region_id,
  founded_precision=excluded.founded_precision, founded_year=excluded.founded_year, founded_month=excluded.founded_month, founded_day=excluded.founded_day, founded_hour=excluded.founded_hour, founded_end_year=excluded.founded_end_year,
  ended_precision=excluded.ended_precision, ended_year=excluded.ended_year, ended_month=excluded.ended_month, ended_day=excluded.ended_day, ended_hour=excluded.ended_hour, ended_end_year=excluded.ended_end_year,
  founder_character_id=excluded.founder_character_id, parent_house_id=excluded.parent_house_id, cadet_branch_of_house_id=excluded.cadet_branch_of_house_id, notes=excluded.notes, status=excluded.status, canonical_status=excluded.canonical_status, origin=excluded.origin;

insert into public.historical_characters (world_scope_id,id,runtime_character_id,lifecycle,name,sex,ancestry_id,homeland_region_id,culture_id,religion_id,birth_precision,birth_year,birth_month,birth_day,birth_hour,birth_end_year,death_precision,death_year,death_month,death_day,death_hour,death_end_year,social_status,house_id,notes,canonical_status,origin)
values
  ('canon','character.vaer_the_red',null,'historical_only','Vaer the Red','male','skeldran','skeldra','skeldran','unknown','approximate',225,null,null,null,null,'approximate',279,null,null,null,null,'ancestral_founder','house.vaering','Claimed ancestral founder of House Vaering; earliest links are partly genealogical tradition rather than courtroom-proof documentation.','traditional','authored'),
  ('canon','character.eirik_ii_vaering',null,'historical_only','Eirik II Vaering','male','skeldran','skeldra','skeldran','unknown','year',497,null,null,null,null,'year',558,null,null,null,null,'royal','house.vaering','Documented royal Vaering line preceding Eirik III.','canonical','authored'),
  ('canon','character.queen_runa',null,'historical_only','Queen Runa','female','skeldran','skeldra','skeldran','unknown','year',503,null,null,null,null,'year',566,null,null,null,null,'queen','house.vaering',null,'canonical','authored'),
  ('canon','character.queen_sigrid',null,'historical_only','Queen Sigrid','female','skeldran','skeldra','skeldran','unknown','year',537,null,null,null,null,'year',598,null,null,null,null,'queen','house.vaering',null,'canonical','authored'),
  ('canon','character.queen_astrid',null,'living_persistent','Queen Astrid Vaering','female','skeldran','skeldra','skeldran','old_gods','year',570,null,null,null,null,'unknown',null,null,null,null,null,'queen','house.vaering','Queen of Skeldra in 628 CR; conservative, deeply religious, and protective of the royal family.','canonical','authored'),
  ('canon','character.hakon_vaering',null,'historical_only','Hakon Vaering','male','skeldran','skeldra','skeldran','unknown','year',568,null,null,null,null,'year',622,null,null,null,null,'prince','house.vaering','Younger royal brother of Eirik IV; father of the politically relevant collateral branch.','canonical','authored'),
  ('canon','character.liv_ormsen',null,'living_persistent','Liv Ormsen','female','skeldran','skeldra','skeldran','unknown','year',573,null,null,null,null,'unknown',null,null,null,null,null,'royal_spouse',null,null,'canonical','authored'),
  ('canon','character.sten_vaering',null,'living_persistent','Sten Vaering','male','skeldran','skeldra','skeldran','old_gods','year',598,null,null,null,null,'unknown',null,null,null,null,null,'royal_collateral','house.vaering','Collateral claimant if the direct Vaering line fractures.','canonical','authored'),
  ('canon','character.yrsa_vaering',null,'living_persistent','Yrsa Vaering','female','skeldran','skeldra','skeldran','old_gods','year',603,null,null,null,null,'unknown',null,null,null,null,null,'royal_collateral','house.vaering',null,'canonical','authored'),
  ('canon','character.aeson_marcellan',null,'historical_only','Aeson Marcellan','male','asterian','asteria','asterian','unknown','approximate',304,null,null,null,null,'approximate',368,null,null,null,null,'statesman','house.marcellan','League-era ancestor and political myth of the Marcellan family; not evidence of a hereditary republican office.','canonical','authored'),
  ('canon','character.decian_marcellan',null,'historical_only','Decian Marcellan','male','asterian','asteria','asterian','unknown','year',538,null,null,null,null,'year',604,null,null,null,null,'senator_naval_financier','house.marcellan',null,'canonical','authored'),
  ('canon','character.lysandra_coris',null,'historical_only','Lysandra Coris','female','asterian','asteria','asterian','unknown','year',543,null,null,null,null,'year',610,null,null,null,null,'patrician',null,null,'canonical','authored'),
  ('canon','character.cassian_marcellan',null,'living_persistent','Cassian Marcellan','male','asterian','asteria','asterian','pantheon','year',571,null,null,null,null,'unknown',null,null,null,null,null,'first_archon','house.marcellan','First Archon in 628 CR; powerful oligarch inside a republic, not a hereditary monarch.','canonical','authored'),
  ('canon','character.thalia_varen',null,'historical_only','Thalia Varen','female','asterian','asteria','asterian','unknown','year',574,null,null,null,null,'year',618,null,null,null,null,'archon_spouse',null,'Late wife of Cassian Marcellan and sister of merchant prince Nikos Varen.','canonical','authored'),
  ('canon','character.helena_marcellan',null,'living_persistent','Helena Marcellan','female','asterian','asteria','asterian','pantheon','year',599,null,null,null,null,'unknown',null,null,null,null,null,'patrician','house.marcellan','Marcellan daughter; politically ambitious and reform-minded, but possesses no hereditary right to the First Archonship.','canonical','authored'),
  ('canon','character.marcus_marcellan',null,'living_persistent','Marcus Marcellan','male','asterian','asteria','asterian','pantheon','year',603,null,null,null,null,'unknown',null,null,null,null,null,'patrician','house.marcellan','Marcellan son; militaristic Pantheon traditionalist, without hereditary entitlement to republican office.','canonical','authored'),
  ('canon','character.lydia_marcellan',null,'living_persistent','Lydia Marcellan','female','asterian','asteria','asterian','unknown','year',575,null,null,null,null,'unknown',null,null,null,null,null,'patrician','house.marcellan','Married into a lesser civic house; spouse remains unnamed in current canon.','canonical','authored'),
  ('canon','character.nikos_varen',null,'living_persistent','Nikos Varen','male','asterian','asteria','asterian','pantheon','year',577,null,null,null,null,'unknown',null,null,null,null,null,'merchant_prince',null,'Brother of the late Thalia Varen; his trade network gives merchant capital a direct family route into Cassian Marcellan''s household.','canonical','authored'),
  ('canon','character.solvar_valerian_i',null,'historical_only','Solvar Valerian I','male','asterian','asteria','asterian','unknown','approximate',34,null,null,null,null,'approximate',102,null,null,null,null,'imperial_ancestor','house.valerian','Celebrated early imperial ancestor; later Valerian genealogy contains multiple imperial and cadet branches.','canonical','authored'),
  ('canon','character.lucan_vi_valerian',null,'historical_only','Lucan VI Valerian','male','asterian','asteria','asterian','unknown','year',526,null,null,null,null,'year',584,null,null,null,null,'imperial','house.valerian',null,'canonical','authored'),
  ('canon','character.aurelia_cassene',null,'historical_only','Aurelia Cassene','female','asterian','asteria','asterian','unknown','year',532,null,null,null,null,'year',590,null,null,null,null,'imperial_spouse',null,null,'canonical','authored'),
  ('canon','character.lucan_vii_valerian',null,'living_persistent','Lucan VII Valerian','male','asterian','asteria','asterian','pantheon','year',560,null,null,null,null,'unknown',null,null,null,null,null,'imperator','house.valerian','Imperator of Aurelia in 628 CR; advocates imperial restoration.','canonical','authored'),
  ('canon','character.marcella_valerian',null,'living_persistent','Empress Marcella Valerian','female','asterian','asteria','asterian','unknown','year',567,null,null,null,null,'unknown',null,null,null,null,null,'empress','house.valerian',null,'canonical','authored'),
  ('canon','character.cassian_valerian',null,'historical_only','Cassian Valerian','male','asterian','asteria','asterian','pantheon','year',586,null,null,null,null,'year',612,null,null,null,null,'imperial_heir','house.valerian','Firstborn of Lucan VII; died at sea without issue in 612 CR.','canonical','authored'),
  ('canon','character.julian_valerian',null,'living_persistent','Julian Valerian','male','asterian','asteria','asterian','pantheon','year',588,null,null,null,null,'unknown',null,null,null,null,null,'military_heir','house.valerian','Current military heir after the death of his elder brother Cassian.','canonical','authored'),
  ('canon','character.livia_valerian',null,'living_persistent','Livia Valerian','female','asterian','asteria','asterian','unknown','year',594,null,null,null,null,'unknown',null,null,null,null,null,'princess','house.valerian','Secret Covenant sympathizer; dynastic descent remains politically relevant even though Julian is the current heir.','canonical','authored'),
  ('canon','character.mattan_i',null,'historical_only','Mattan I','male','serathi','serath','serathi','unknown','approximate',450,null,null,null,null,'approximate',510,null,null,null,null,'king',null,'Pre-Covenant king in the older dynasty.','canonical','authored'),
  ('canon','character.ashar_i_asharan',null,'historical_only','Ashar I','male','serathi','serath','serathi','covenant','approximate',477,null,null,null,null,'approximate',538,null,null,null,null,'king','house.asharan','Converted publicly in 503 CR and became king in 508; the dynasty was thereafter styled Asharan.','canonical','authored'),
  ('canon','character.jonan_i_asharan',null,'historical_only','Jonan I Asharan','male','serathi','serath','serathi','covenant','year',510,null,null,null,null,'year',574,null,null,null,null,'royal','house.asharan',null,'canonical','authored'),
  ('canon','character.mattan_ii_asharan',null,'historical_only','Mattan II Asharan','male','serathi','serath','serathi','covenant','year',541,null,null,null,null,'year',607,null,null,null,null,'royal','house.asharan',null,'canonical','authored'),
  ('canon','character.mattan_iii_asharan',null,'living_persistent','Mattan III Asharan','male','serathi','serath','serathi','covenant','year',573,null,null,null,null,'unknown',null,null,null,null,null,'king','house.asharan','King of Serath in 628 CR.','canonical','authored'),
  ('canon','character.queen_miriam_asharan',null,'living_persistent','Queen Miriam Asharan','female','serathi','serath','serathi','covenant','year',579,null,null,null,null,'unknown',null,null,null,null,null,'queen','house.asharan',null,'canonical','authored'),
  ('canon','character.elias_asharan',null,'living_persistent','Elias Asharan','male','serathi','serath','serathi','covenant','year',600,null,null,null,null,'unknown',null,null,null,null,null,'crown_prince','house.asharan','Crown Prince; sincerely supports military protection of Covenant believers abroad.','canonical','authored'),
  ('canon','character.salome_asharan',null,'living_persistent','Salome Asharan','female','serathi','serath','serathi','covenant','year',603,null,null,null,null,'unknown',null,null,null,null,null,'princess','house.asharan',null,'canonical','authored'),
  ('canon','character.jonan_asharan',null,'living_persistent','Jonan Asharan','male','serathi','serath','serathi','covenant','year',609,null,null,null,null,'unknown',null,null,null,null,null,'prince','house.asharan',null,'canonical','authored'),
  ('canon','character.tenrai_shun',null,'historical_only','Tenrai Shun','male','kaishin','kaishin','kaishin','turning_wheel','approximate',318,null,null,null,null,'approximate',377,null,null,null,null,'imperial_ancestor','house.tenrai','Centralizing reform ancestor; current canon does not claim he founded the house itself.','canonical','authored'),
  ('canon','character.kaito_tenrai',null,'historical_only','Emperor Kaito Tenrai','male','kaishin','kaishin','kaishin','turning_wheel','year',533,null,null,null,null,'year',601,null,null,null,null,'emperor','house.tenrai',null,'canonical','authored'),
  ('canon','character.hana_tenrai',null,'historical_only','Empress Hana','female','kaishin','kaishin','kaishin','turning_wheel','year',538,null,null,null,null,'year',612,null,null,null,null,'empress','house.tenrai',null,'canonical','authored'),
  ('canon','character.jian_tenrai',null,'living_persistent','Emperor Jian Tenrai','male','kaishin','kaishin','kaishin','turning_wheel','year',567,null,null,null,null,'unknown',null,null,null,null,null,'emperor','house.tenrai','Emperor of Kaishin in 628 CR.','canonical','authored'),
  ('canon','character.mei_tenrai',null,'living_persistent','Empress Mei Tenrai','female','kaishin','kaishin','kaishin','turning_wheel','year',572,null,null,null,null,'unknown',null,null,null,null,null,'empress','house.tenrai',null,'canonical','authored'),
  ('canon','character.ren_tenrai',null,'living_persistent','Ren Tenrai','male','kaishin','kaishin','kaishin','turning_wheel','year',593,null,null,null,null,'unknown',null,null,null,null,null,'crown_prince','house.tenrai','Crown Prince and selective modernizer.','canonical','authored'),
  ('canon','character.daichi_tenrai',null,'living_persistent','Daichi Tenrai','male','kaishin','kaishin','kaishin','turning_wheel','year',597,null,null,null,null,'unknown',null,null,null,null,null,'prince','house.tenrai','Traditionalist prince suspicious of foreign institutional dependence.','canonical','authored'),
  ('canon','character.aya_tenrai',null,'living_persistent','Aya Tenrai','female','kaishin','kaishin','kaishin','turning_wheel','year',601,null,null,null,null,'unknown',null,null,null,null,null,'princess','house.tenrai','Princess with strong interest in foreign cultures and intellectual exchange.','canonical','authored'),
  ('canon','character.niketas_ii_darcon',null,'historical_only','Emperor Niketas II Darcon','male','asterian','crossroads','vesperan','unknown','year',520,null,null,null,null,'year',576,null,null,null,null,'emperor','house.darcon',null,'canonical','authored'),
  ('canon','character.callista_darcon',null,'historical_only','Empress Callista','female','asterian','crossroads','vesperan','unknown','year',525,null,null,null,null,'year',580,null,null,null,null,'empress','house.darcon',null,'canonical','authored'),
  ('canon','character.alexar_ii_darcon',null,'historical_only','Alexar II Darcon','male','asterian','crossroads','vesperan','unknown','year',548,null,null,null,null,'year',602,null,null,null,null,'imperial','house.darcon','Used marriage, toll concessions, fortification, and religious balancing to keep Vespera independent.','canonical','authored'),
  ('canon','character.sophia_valen',null,'historical_only','Sophia Valen','female','asterian','crossroads','vesperan','unknown','year',555,null,null,null,null,'year',585,null,null,null,null,'imperial_spouse',null,null,'canonical','authored'),
  ('canon','character.miriam_sariel',null,'historical_only','Miriam Sariel','female','serathi','crossroads','vesperan','covenant','year',558,null,null,null,null,'year',616,null,null,null,null,'imperial_spouse',null,'Covenant noblewoman; married Alexar II in 587 CR, creating an interfaith court precedent.','canonical','authored'),
  ('canon','character.alexar_iii_darcon',null,'living_persistent','Emperor Alexar III Darcon','male','asterian','crossroads','vesperan','pantheon','year',576,null,null,null,null,'unknown',null,null,null,null,null,'emperor','house.darcon','Emperor of Vespera in 628 CR; balances stronger powers and a religiously mixed capital.','canonical','authored'),
  ('canon','character.helena_celos_darcon',null,'living_persistent','Empress Helena Celos','female','serathi','crossroads','vesperan','covenant','year',583,null,null,null,null,'unknown',null,null,null,null,null,'empress','house.darcon','Covenant empress whose marriage to Alexar III is itself politically important.','canonical','authored'),
  ('canon','character.adrian_darcon',null,'living_persistent','Adrian Darcon','male','mixed','crossroads','vesperan','unaffiliated','year',605,null,null,null,null,'unknown',null,null,null,null,null,'prince','house.darcon','Religion unsettled; both Pantheon and Covenant factions court him. Exact succession precedence is intentionally unresolved.','canonical','authored'),
  ('canon','character.sophia_darcon',null,'living_persistent','Sophia Darcon','female','mixed','crossroads','vesperan','covenant','year',608,null,null,null,null,'unknown',null,null,null,null,null,'princess','house.darcon','Popular with Vespera''s Covenant population; exact succession precedence is intentionally unresolved.','canonical','authored'),
  ('canon','character.mateo_corven',null,'historical_only','Mateo Corven','male','unknown','outer_isles','outer_isles','unknown','year',558,null,null,null,null,'year',612,null,null,null,null,'merchant_captain',null,null,'canonical','authored'),
  ('canon','character.isabella_corven',null,'living_persistent','Isabella Corven','female','asterian','outer_isles','outer_isles','pantheon','year',590,null,null,null,null,'unknown',null,null,null,null,null,'pirate_captain',null,'Captain of Gilded Knife; Day-1 High Captain contender and organizer. Her mother''s office creates networks, not hereditary entitlement.','canonical','authored'),
  ('canon','character.soren_voss',null,'historical_only','Soren Voss','male','skeldran','outer_isles','outer_isles','unknown','year',551,null,null,null,null,'year',602,null,null,null,null,'privateer_smuggler',null,null,'canonical','authored'),
  ('canon','character.daphne_merys',null,'historical_only','Daphne Merys','female','asterian','outer_isles','outer_isles','unknown','year',557,null,null,null,null,'year',614,null,null,null,null,'navigator_trader',null,null,'canonical','authored'),
  ('canon','character.cal_voss',null,'historical_only','Cal Voss','male','mixed','outer_isles','outer_isles','unknown','year',589,null,null,null,null,'year',616,null,null,null,null,'mariner',null,'Younger brother of Mara Voss; died at sea without surviving children.','canonical','authored'),
  ('canon','character.damon_rhys',null,'living_persistent','Damon Rhys','male','asterian','asteria','asterian','unknown','year',570,null,null,null,null,'unknown',null,null,null,null,null,'sea_magistrate',null,'Elected Sea Magistrate of Rhadessa in 628 CR; long compromise career, with the current term ending soon. His children do not inherit the office.','canonical','authored')
on conflict (world_scope_id,id) do update set
  runtime_character_id=excluded.runtime_character_id, lifecycle=excluded.lifecycle, name=excluded.name, sex=excluded.sex, ancestry_id=excluded.ancestry_id, homeland_region_id=excluded.homeland_region_id, culture_id=excluded.culture_id, religion_id=excluded.religion_id,
  birth_precision=excluded.birth_precision, birth_year=excluded.birth_year, birth_month=excluded.birth_month, birth_day=excluded.birth_day, birth_hour=excluded.birth_hour, birth_end_year=excluded.birth_end_year,
  death_precision=excluded.death_precision, death_year=excluded.death_year, death_month=excluded.death_month, death_day=excluded.death_day, death_hour=excluded.death_hour, death_end_year=excluded.death_end_year,
  social_status=excluded.social_status, house_id=excluded.house_id, notes=excluded.notes, canonical_status=excluded.canonical_status, origin=excluded.origin;

insert into public.historical_relationships (world_scope_id,id,from_character_id,to_character_id,relationship_type,start_precision,start_year,start_month,start_day,start_hour,start_end_year,end_precision,end_year,end_month,end_day,end_hour,end_end_year,end_reason,canonical_status,origin)
values
  ('canon','relationship.eirik_ii.spouse.runa','character.eirik_ii_vaering','character.queen_runa','spouse','unknown',null,null,null,null,null,'year',558,null,null,null,null,'death','canonical','authored'),
  ('canon','relationship.eirik_ii.parent.eirik_iii','character.eirik_ii_vaering','character.eirik_iii_vaering','parent','year',533,null,null,null,null,'year',558,null,null,null,null,'death','canonical','authored'),
  ('canon','relationship.runa.parent.eirik_iii','character.queen_runa','character.eirik_iii_vaering','parent','year',533,null,null,null,null,'year',566,null,null,null,null,'death','canonical','authored'),
  ('canon','relationship.eirik_iii.spouse.sigrid','character.eirik_iii_vaering','character.queen_sigrid','spouse','unknown',null,null,null,null,null,'year',598,null,null,null,null,'death','canonical','authored'),
  ('canon','relationship.sigrid.parent.eirik_iv','character.queen_sigrid','character.eirik_iv_vaering','parent','year',565,null,null,null,null,'year',598,null,null,null,null,'death','canonical','authored'),
  ('canon','relationship.eirik_iii.parent.hakon','character.eirik_iii_vaering','character.hakon_vaering','parent','year',568,null,null,null,null,'year',613,null,null,null,null,'death','canonical','authored'),
  ('canon','relationship.sigrid.parent.hakon','character.queen_sigrid','character.hakon_vaering','parent','year',568,null,null,null,null,'year',598,null,null,null,null,'death','canonical','authored'),
  ('canon','relationship.eirik_iv.spouse.astrid','character.eirik_iv_vaering','character.queen_astrid','spouse','unknown',null,null,null,null,null,'unknown',null,null,null,null,null,null,'canonical','authored'),
  ('canon','relationship.astrid.parent.leif','character.queen_astrid','character.leif_vaering','parent','year',592,null,null,null,null,'unknown',null,null,null,null,null,null,'canonical','authored'),
  ('canon','relationship.astrid.parent.freya','character.queen_astrid','character.freya_vaering','parent','year',596,null,null,null,null,'unknown',null,null,null,null,null,null,'canonical','authored'),
  ('canon','relationship.astrid.parent.torvald','character.queen_astrid','character.torvald_vaering','parent','year',604,null,null,null,null,'unknown',null,null,null,null,null,null,'canonical','authored'),
  ('canon','relationship.hakon.spouse.liv','character.hakon_vaering','character.liv_ormsen','spouse','unknown',null,null,null,null,null,'year',622,null,null,null,null,'death','canonical','authored'),
  ('canon','relationship.hakon.parent.sten','character.hakon_vaering','character.sten_vaering','parent','year',598,null,null,null,null,'year',622,null,null,null,null,'death','canonical','authored'),
  ('canon','relationship.liv.parent.sten','character.liv_ormsen','character.sten_vaering','parent','year',598,null,null,null,null,'unknown',null,null,null,null,null,null,'canonical','authored'),
  ('canon','relationship.hakon.parent.yrsa','character.hakon_vaering','character.yrsa_vaering','parent','year',603,null,null,null,null,'year',622,null,null,null,null,'death','canonical','authored'),
  ('canon','relationship.liv.parent.yrsa','character.liv_ormsen','character.yrsa_vaering','parent','year',603,null,null,null,null,'unknown',null,null,null,null,null,null,'canonical','authored'),
  ('canon','relationship.decian.spouse.lysandra','character.decian_marcellan','character.lysandra_coris','spouse','unknown',null,null,null,null,null,'year',604,null,null,null,null,'death','canonical','authored'),
  ('canon','relationship.decian.parent.cassian','character.decian_marcellan','character.cassian_marcellan','parent','year',571,null,null,null,null,'year',604,null,null,null,null,'death','canonical','authored'),
  ('canon','relationship.lysandra.parent.cassian','character.lysandra_coris','character.cassian_marcellan','parent','year',571,null,null,null,null,'year',610,null,null,null,null,'death','canonical','authored'),
  ('canon','relationship.decian.parent.lydia','character.decian_marcellan','character.lydia_marcellan','parent','year',575,null,null,null,null,'year',604,null,null,null,null,'death','canonical','authored'),
  ('canon','relationship.lysandra.parent.lydia','character.lysandra_coris','character.lydia_marcellan','parent','year',575,null,null,null,null,'year',610,null,null,null,null,'death','canonical','authored'),
  ('canon','relationship.cassian.spouse.thalia','character.cassian_marcellan','character.thalia_varen','spouse','unknown',null,null,null,null,null,'year',618,null,null,null,null,'death','canonical','authored'),
  ('canon','relationship.cassian.parent.helena','character.cassian_marcellan','character.helena_marcellan','parent','year',599,null,null,null,null,'unknown',null,null,null,null,null,null,'canonical','authored'),
  ('canon','relationship.thalia.parent.helena','character.thalia_varen','character.helena_marcellan','parent','year',599,null,null,null,null,'year',618,null,null,null,null,'death','canonical','authored'),
  ('canon','relationship.cassian.parent.marcus','character.cassian_marcellan','character.marcus_marcellan','parent','year',603,null,null,null,null,'unknown',null,null,null,null,null,null,'canonical','authored'),
  ('canon','relationship.thalia.parent.marcus','character.thalia_varen','character.marcus_marcellan','parent','year',603,null,null,null,null,'year',618,null,null,null,null,'death','canonical','authored'),
  ('canon','relationship.thalia.sibling.nikos','character.thalia_varen','character.nikos_varen','sibling','year',577,null,null,null,null,'year',618,null,null,null,null,'death','canonical','authored'),
  ('canon','relationship.lucan_vi.spouse.aurelia','character.lucan_vi_valerian','character.aurelia_cassene','spouse','unknown',null,null,null,null,null,'year',584,null,null,null,null,'death','canonical','authored'),
  ('canon','relationship.lucan_vi.parent.lucan_vii','character.lucan_vi_valerian','character.lucan_vii_valerian','parent','year',560,null,null,null,null,'year',584,null,null,null,null,'death','canonical','authored'),
  ('canon','relationship.aurelia.parent.lucan_vii','character.aurelia_cassene','character.lucan_vii_valerian','parent','year',560,null,null,null,null,'year',590,null,null,null,null,'death','canonical','authored'),
  ('canon','relationship.lucan_vii.spouse.marcella','character.lucan_vii_valerian','character.marcella_valerian','spouse','unknown',null,null,null,null,null,'unknown',null,null,null,null,null,null,'canonical','authored'),
  ('canon','relationship.lucan_vii.parent.cassian','character.lucan_vii_valerian','character.cassian_valerian','parent','year',586,null,null,null,null,'year',612,null,null,null,null,'death','canonical','authored'),
  ('canon','relationship.marcella.parent.cassian','character.marcella_valerian','character.cassian_valerian','parent','year',586,null,null,null,null,'year',612,null,null,null,null,'death','canonical','authored'),
  ('canon','relationship.lucan_vii.parent.julian','character.lucan_vii_valerian','character.julian_valerian','parent','year',588,null,null,null,null,'unknown',null,null,null,null,null,null,'canonical','authored'),
  ('canon','relationship.marcella.parent.julian','character.marcella_valerian','character.julian_valerian','parent','year',588,null,null,null,null,'unknown',null,null,null,null,null,null,'canonical','authored'),
  ('canon','relationship.lucan_vii.parent.livia','character.lucan_vii_valerian','character.livia_valerian','parent','year',594,null,null,null,null,'unknown',null,null,null,null,null,null,'canonical','authored'),
  ('canon','relationship.marcella.parent.livia','character.marcella_valerian','character.livia_valerian','parent','year',594,null,null,null,null,'unknown',null,null,null,null,null,null,'canonical','authored'),
  ('canon','relationship.mattan_i.parent.ashar_i','character.mattan_i','character.ashar_i_asharan','parent','approximate',477,null,null,null,null,'approximate',510,null,null,null,null,'death','canonical','authored'),
  ('canon','relationship.ashar_i.parent.jonan_i','character.ashar_i_asharan','character.jonan_i_asharan','parent','year',510,null,null,null,null,'approximate',538,null,null,null,null,'death','canonical','authored'),
  ('canon','relationship.jonan_i.parent.mattan_ii','character.jonan_i_asharan','character.mattan_ii_asharan','parent','year',541,null,null,null,null,'year',574,null,null,null,null,'death','canonical','authored'),
  ('canon','relationship.mattan_ii.parent.mattan_iii','character.mattan_ii_asharan','character.mattan_iii_asharan','parent','year',573,null,null,null,null,'year',607,null,null,null,null,'death','canonical','authored'),
  ('canon','relationship.mattan_iii.spouse.miriam','character.mattan_iii_asharan','character.queen_miriam_asharan','spouse','unknown',null,null,null,null,null,'unknown',null,null,null,null,null,null,'canonical','authored'),
  ('canon','relationship.mattan_iii.parent.elias','character.mattan_iii_asharan','character.elias_asharan','parent','year',600,null,null,null,null,'unknown',null,null,null,null,null,null,'canonical','authored'),
  ('canon','relationship.miriam.parent.elias','character.queen_miriam_asharan','character.elias_asharan','parent','year',600,null,null,null,null,'unknown',null,null,null,null,null,null,'canonical','authored'),
  ('canon','relationship.mattan_iii.parent.salome','character.mattan_iii_asharan','character.salome_asharan','parent','year',603,null,null,null,null,'unknown',null,null,null,null,null,null,'canonical','authored'),
  ('canon','relationship.miriam.parent.salome','character.queen_miriam_asharan','character.salome_asharan','parent','year',603,null,null,null,null,'unknown',null,null,null,null,null,null,'canonical','authored'),
  ('canon','relationship.mattan_iii.parent.jonan','character.mattan_iii_asharan','character.jonan_asharan','parent','year',609,null,null,null,null,'unknown',null,null,null,null,null,null,'canonical','authored'),
  ('canon','relationship.miriam.parent.jonan','character.queen_miriam_asharan','character.jonan_asharan','parent','year',609,null,null,null,null,'unknown',null,null,null,null,null,null,'canonical','authored'),
  ('canon','relationship.kaito.spouse.hana','character.kaito_tenrai','character.hana_tenrai','spouse','unknown',null,null,null,null,null,'year',601,null,null,null,null,'death','canonical','authored'),
  ('canon','relationship.kaito.parent.jian','character.kaito_tenrai','character.jian_tenrai','parent','year',567,null,null,null,null,'year',601,null,null,null,null,'death','canonical','authored'),
  ('canon','relationship.hana.parent.jian','character.hana_tenrai','character.jian_tenrai','parent','year',567,null,null,null,null,'year',612,null,null,null,null,'death','canonical','authored'),
  ('canon','relationship.jian.spouse.mei','character.jian_tenrai','character.mei_tenrai','spouse','unknown',null,null,null,null,null,'unknown',null,null,null,null,null,null,'canonical','authored'),
  ('canon','relationship.jian.parent.ren','character.jian_tenrai','character.ren_tenrai','parent','year',593,null,null,null,null,'unknown',null,null,null,null,null,null,'canonical','authored'),
  ('canon','relationship.mei.parent.ren','character.mei_tenrai','character.ren_tenrai','parent','year',593,null,null,null,null,'unknown',null,null,null,null,null,null,'canonical','authored'),
  ('canon','relationship.jian.parent.daichi','character.jian_tenrai','character.daichi_tenrai','parent','year',597,null,null,null,null,'unknown',null,null,null,null,null,null,'canonical','authored'),
  ('canon','relationship.mei.parent.daichi','character.mei_tenrai','character.daichi_tenrai','parent','year',597,null,null,null,null,'unknown',null,null,null,null,null,null,'canonical','authored'),
  ('canon','relationship.jian.parent.aya','character.jian_tenrai','character.aya_tenrai','parent','year',601,null,null,null,null,'unknown',null,null,null,null,null,null,'canonical','authored'),
  ('canon','relationship.mei.parent.aya','character.mei_tenrai','character.aya_tenrai','parent','year',601,null,null,null,null,'unknown',null,null,null,null,null,null,'canonical','authored'),
  ('canon','relationship.niketas_ii.spouse.callista','character.niketas_ii_darcon','character.callista_darcon','spouse','unknown',null,null,null,null,null,'year',576,null,null,null,null,'death','canonical','authored'),
  ('canon','relationship.niketas_ii.parent.alexar_ii','character.niketas_ii_darcon','character.alexar_ii_darcon','parent','year',548,null,null,null,null,'year',576,null,null,null,null,'death','canonical','authored'),
  ('canon','relationship.callista.parent.alexar_ii','character.callista_darcon','character.alexar_ii_darcon','parent','year',548,null,null,null,null,'year',580,null,null,null,null,'death','canonical','authored'),
  ('canon','relationship.alexar_ii.spouse.sophia_valen','character.alexar_ii_darcon','character.sophia_valen','spouse','unknown',null,null,null,null,null,'year',585,null,null,null,null,'death','canonical','authored'),
  ('canon','relationship.alexar_ii.parent.alexar_iii','character.alexar_ii_darcon','character.alexar_iii_darcon','parent','year',576,null,null,null,null,'year',602,null,null,null,null,'death','canonical','authored'),
  ('canon','relationship.sophia_valen.parent.alexar_iii','character.sophia_valen','character.alexar_iii_darcon','parent','year',576,null,null,null,null,'year',585,null,null,null,null,'death','canonical','authored'),
  ('canon','relationship.alexar_ii.spouse.miriam_sariel','character.alexar_ii_darcon','character.miriam_sariel','spouse','year',587,null,null,null,null,'year',602,null,null,null,null,'death','canonical','authored'),
  ('canon','relationship.alexar_iii.spouse.helena','character.alexar_iii_darcon','character.helena_celos_darcon','spouse','unknown',null,null,null,null,null,'unknown',null,null,null,null,null,null,'canonical','authored'),
  ('canon','relationship.alexar_iii.parent.adrian','character.alexar_iii_darcon','character.adrian_darcon','parent','year',605,null,null,null,null,'unknown',null,null,null,null,null,null,'canonical','authored'),
  ('canon','relationship.helena.parent.adrian','character.helena_celos_darcon','character.adrian_darcon','parent','year',605,null,null,null,null,'unknown',null,null,null,null,null,null,'canonical','authored'),
  ('canon','relationship.alexar_iii.parent.sophia','character.alexar_iii_darcon','character.sophia_darcon','parent','year',608,null,null,null,null,'unknown',null,null,null,null,null,null,'canonical','authored'),
  ('canon','relationship.helena.parent.sophia','character.helena_celos_darcon','character.sophia_darcon','parent','year',608,null,null,null,null,'unknown',null,null,null,null,null,null,'canonical','authored'),
  ('canon','relationship.jessa.spouse.mateo','character.jessa_corven','character.mateo_corven','spouse','unknown',null,null,null,null,null,'year',607,null,null,null,null,'death','canonical','authored'),
  ('canon','relationship.jessa.parent.isabella','character.jessa_corven','character.isabella_corven','parent','year',590,null,null,null,null,'year',607,null,null,null,null,'death','canonical','authored'),
  ('canon','relationship.mateo.parent.isabella','character.mateo_corven','character.isabella_corven','parent','year',590,null,null,null,null,'year',612,null,null,null,null,'death','canonical','authored'),
  ('canon','relationship.soren.spouse.daphne','character.soren_voss','character.daphne_merys','spouse','unknown',null,null,null,null,null,'year',602,null,null,null,null,'death','canonical','authored'),
  ('canon','relationship.soren.parent.mara','character.soren_voss','character.mara_voss','parent','year',584,null,null,null,null,'year',602,null,null,null,null,'death','canonical','authored'),
  ('canon','relationship.daphne.parent.mara','character.daphne_merys','character.mara_voss','parent','year',584,null,null,null,null,'year',614,null,null,null,null,'death','canonical','authored'),
  ('canon','relationship.soren.parent.cal','character.soren_voss','character.cal_voss','parent','year',589,null,null,null,null,'year',602,null,null,null,null,'death','canonical','authored'),
  ('canon','relationship.daphne.parent.cal','character.daphne_merys','character.cal_voss','parent','year',589,null,null,null,null,'year',614,null,null,null,null,'death','canonical','authored')
on conflict (world_scope_id,id) do nothing;

insert into public.offices (world_scope_id,id,name,institution_id,region_id,selection_mode,hereditary_by_default,notes,canonical_status,origin)
values
  ('canon','office.asterra.first_archon','First Archon of Asterra',null,'asteria','elected',false,'Republican office. Marcellan family power can influence elections but children do not inherit this office by blood.','canonical','authored'),
  ('canon','office.aurelia.imperator','Imperator of Aurelia',null,'asteria','hereditary',true,'Imperial office. Dynastic descent matters, but future succession must still consider legitimacy and political/military support rather than a universal hard-coded rule.','canonical','authored'),
  ('canon','office.serath.king','King of Serath',null,'serath','hereditary',true,'Serathi royal office. Covenant legitimacy and dynastic descent both matter.','canonical','authored'),
  ('canon','office.kaishin.emperor','Emperor of Kaishin',null,'kaishin','hereditary',true,'Imperial Tenrai office; court institutions and continuity matter alongside descent.','canonical','authored'),
  ('canon','office.vespera.emperor','Emperor of Vespera',null,'crossroads','customary',true,'Dynastic office whose practical succession can depend on court, military, religious, and diplomatic legitimacy; not reduced to strict primogeniture.','canonical','authored'),
  ('canon','office.rhadessa.sea_magistrate','Sea Magistrate of Rhadessa',null,'asteria','elected',false,'Elected ruler chosen from naval families. Family reputation may matter, but descendants receive no automatic political succession.','canonical','authored')
on conflict (world_scope_id,id) do update set name=excluded.name,institution_id=excluded.institution_id,region_id=excluded.region_id,selection_mode=excluded.selection_mode,hereditary_by_default=excluded.hereditary_by_default,notes=excluded.notes,canonical_status=excluded.canonical_status,origin=excluded.origin;

insert into public.office_terms (world_scope_id,id,office_id,holder_character_id,start_precision,start_year,start_month,start_day,start_hour,start_end_year,end_precision,end_year,end_month,end_day,end_hour,end_end_year,end_reason,interim,canonical_status,origin)
values
  ('canon','term.asterra.cassian_marcellan','office.asterra.first_archon','character.cassian_marcellan','unknown',null,null,null,null,null,'unknown',null,null,null,null,null,null,false,'canonical','authored'),
  ('canon','term.aurelia.lucan_vii','office.aurelia.imperator','character.lucan_vii_valerian','unknown',null,null,null,null,null,'unknown',null,null,null,null,null,null,false,'canonical','authored'),
  ('canon','term.serath.ashar_i','office.serath.king','character.ashar_i_asharan','year',508,null,null,null,null,'approximate',538,null,null,null,null,'death',false,'canonical','authored'),
  ('canon','term.serath.mattan_iii','office.serath.king','character.mattan_iii_asharan','unknown',null,null,null,null,null,'unknown',null,null,null,null,null,null,false,'canonical','authored'),
  ('canon','term.kaishin.kaito_tenrai','office.kaishin.emperor','character.kaito_tenrai','unknown',null,null,null,null,null,'year',601,null,null,null,null,'death',false,'canonical','authored'),
  ('canon','term.kaishin.jian_tenrai','office.kaishin.emperor','character.jian_tenrai','unknown',null,null,null,null,null,'unknown',null,null,null,null,null,null,false,'canonical','authored'),
  ('canon','term.vespera.niketas_ii','office.vespera.emperor','character.niketas_ii_darcon','unknown',null,null,null,null,null,'year',576,null,null,null,null,'death',false,'canonical','authored'),
  ('canon','term.vespera.alexar_iii','office.vespera.emperor','character.alexar_iii_darcon','unknown',null,null,null,null,null,'unknown',null,null,null,null,null,null,false,'canonical','authored'),
  ('canon','term.rhadessa.damon_rhys','office.rhadessa.sea_magistrate','character.damon_rhys','unknown',null,null,null,null,null,'unknown',null,null,null,null,null,'term_ending_soon',false,'canonical','authored')
on conflict (world_scope_id,id) do nothing;

insert into public.historical_claims (world_scope_id,id,claimant_character_id,target_office_id,basis,strength,priority,legal_basis,genealogical_path,disputed,active,start_precision,start_year,start_month,start_day,start_hour,start_end_year,end_precision,end_year,end_month,end_day,end_hour,end_end_year,canonical_status,origin)
values
  ('canon','claim.freya.skeldran_crown.descent','character.freya_vaering','office.skeldra.king','direct_descent',null,null,'Direct child of Eirik IV. Leif remains the recognized legal heir.','["character.freya_vaering","character.eirik_iv_vaering"]'::jsonb,false,true,'unknown',null,null,null,null,null,'unknown',null,null,null,null,null,'canonical','authored'),
  ('canon','claim.freya.skeldran_crown.custom','character.freya_vaering','office.skeldra.king','customary_law',null,null,'Traditionalist and military support could invoke ancestral/customary arguments if succession fractures; this is not the current legal-heir designation.','[]'::jsonb,true,true,'unknown',null,null,null,null,null,'unknown',null,null,null,null,null,'canonical_uncertain','authored'),
  ('canon','claim.torvald.skeldran_crown','character.torvald_vaering','office.skeldra.king','direct_descent',null,null,'Direct child of Eirik IV, junior to the recognized legal heir; no exact statutory priority is invented here.','["character.torvald_vaering","character.eirik_iv_vaering"]'::jsonb,false,true,'unknown',null,null,null,null,null,'unknown',null,null,null,null,null,'canonical','authored'),
  ('canon','claim.sten.skeldran_crown','character.sten_vaering','office.skeldra.king','collateral_descent',null,null,'Collateral Vaering claim if the direct line fractures.','["character.sten_vaering","character.hakon_vaering","character.eirik_iii_vaering","character.eirik_iv_vaering"]'::jsonb,false,false,'unknown',null,null,null,null,null,'unknown',null,null,null,null,null,'canonical','authored'),
  ('canon','claim.cassian.asterra_first_archon','character.cassian_marcellan','office.asterra.first_archon','election',null,null,'Current republican mandate. Marcellan wealth and patronage influence politics but do not convert the office into a crown.','[]'::jsonb,false,true,'unknown',null,null,null,null,null,'unknown',null,null,null,null,null,'canonical','authored'),
  ('canon','claim.julian.aurellian_imperator','character.julian_valerian','office.aurelia.imperator','direct_descent',null,1,'Current military heir after elder brother Cassian died without issue in 612 CR.','["character.julian_valerian","character.lucan_vii_valerian"]'::jsonb,false,true,'year',612,null,null,null,null,'unknown',null,null,null,null,null,'canonical','authored'),
  ('canon','claim.livia.aurellian_imperator','character.livia_valerian','office.aurelia.imperator','direct_descent',null,null,'Dynastic descent remains a potential basis; Julian is the current recognized military heir.','["character.livia_valerian","character.lucan_vii_valerian"]'::jsonb,false,true,'unknown',null,null,null,null,null,'unknown',null,null,null,null,null,'canonical','authored'),
  ('canon','claim.elias.serathi_crown','character.elias_asharan','office.serath.king','direct_descent',null,1,'Recognized Crown Prince in 628 CR.','["character.elias_asharan","character.mattan_iii_asharan"]'::jsonb,false,true,'unknown',null,null,null,null,null,'unknown',null,null,null,null,null,'canonical','authored'),
  ('canon','claim.salome.serathi_crown','character.salome_asharan','office.serath.king','direct_descent',null,null,'Direct royal descent; exact contingent precedence behind Elias is intentionally not fabricated.','["character.salome_asharan","character.mattan_iii_asharan"]'::jsonb,false,true,'unknown',null,null,null,null,null,'unknown',null,null,null,null,null,'canonical','authored'),
  ('canon','claim.jonan.serathi_crown','character.jonan_asharan','office.serath.king','direct_descent',null,null,'Direct royal descent; exact contingent precedence behind Elias is intentionally not fabricated.','["character.jonan_asharan","character.mattan_iii_asharan"]'::jsonb,false,true,'unknown',null,null,null,null,null,'unknown',null,null,null,null,null,'canonical','authored'),
  ('canon','claim.ren.kaishin_throne','character.ren_tenrai','office.kaishin.emperor','direct_descent',null,1,'Recognized Crown Prince in 628 CR.','["character.ren_tenrai","character.jian_tenrai"]'::jsonb,false,true,'unknown',null,null,null,null,null,'unknown',null,null,null,null,null,'canonical','authored'),
  ('canon','claim.daichi.kaishin_throne','character.daichi_tenrai','office.kaishin.emperor','direct_descent',null,null,'Direct imperial descent; no exact contingent precedence beyond Ren is invented.','["character.daichi_tenrai","character.jian_tenrai"]'::jsonb,false,true,'unknown',null,null,null,null,null,'unknown',null,null,null,null,null,'canonical','authored'),
  ('canon','claim.aya.kaishin_throne','character.aya_tenrai','office.kaishin.emperor','direct_descent',null,null,'Direct imperial descent; no exact contingent precedence beyond Ren is invented.','["character.aya_tenrai","character.jian_tenrai"]'::jsonb,false,true,'unknown',null,null,null,null,null,'unknown',null,null,null,null,null,'canonical','authored'),
  ('canon','claim.adrian.vesperan_throne','character.adrian_darcon','office.vespera.emperor','direct_descent',null,null,'Direct imperial descent. Exact succession precedence is not yet canonized and Vesperan legitimacy is not strict primogeniture.','["character.adrian_darcon","character.alexar_iii_darcon"]'::jsonb,false,true,'unknown',null,null,null,null,null,'unknown',null,null,null,null,null,'canonical_uncertain','authored'),
  ('canon','claim.sophia.vesperan_throne','character.sophia_darcon','office.vespera.emperor','direct_descent',null,null,'Direct imperial descent. Exact succession precedence is not yet canonized; religious support can affect practical legitimacy.','["character.sophia_darcon","character.alexar_iii_darcon"]'::jsonb,false,true,'unknown',null,null,null,null,null,'unknown',null,null,null,null,null,'canonical_uncertain','authored'),
  ('canon','claim.mara.blackhaven_high_captain','character.mara_voss','office.blackhaven.high_captain','election',null,null,'Won the 623 election through alliances, profitable raids, reputation, crew loyalty, and rival coalition arithmetic.','[]'::jsonb,false,true,'year',623,null,null,null,null,'unknown',null,null,null,null,null,'canonical','authored'),
  ('canon','claim.isabella.blackhaven_high_captain','character.isabella_corven','office.blackhaven.high_captain','election',null,null,'Recognized Day-1 contender. Jessa Corven''s legacy supplies networks and reputation, not inheritance of office.','[]'::jsonb,false,true,'unknown',null,null,null,null,null,'unknown',null,null,null,null,null,'canonical','authored'),
  ('canon','claim.damon.rhadessa_sea_magistrate','character.damon_rhys','office.rhadessa.sea_magistrate','election',null,null,'Current elected mandate near the end of its term; family does not create automatic succession.','[]'::jsonb,false,true,'unknown',null,null,null,null,null,'unknown',null,null,null,null,null,'canonical','authored')
on conflict (world_scope_id,id) do nothing;

insert into public.historical_events (world_scope_id,id,event_type,title,date_precision,date_year,date_month,date_day,date_hour,date_end_year,location_id,description,canonical_status,origin,source_confidence,created_by_system,imported_from_seed,simulation_event_id)
values
  ('canon','history.event.ashar_conversion.503','conversion','Public Conversion of Ashar I','year',503,null,null,null,null,'region.serath','Ashar I publicly converted to the Covenant in 503 CR, helping reshape royal legitimacy.','canonical','authored',100,null,'0.6B',null),
  ('canon','history.event.ashar_kingship.508','coronation','Ashar I becomes King','year',508,null,null,null,null,'region.serath','Ashar I became king in 508 CR; the dynasty was thereafter styled Asharan.','canonical','authored',100,null,'0.6B',null),
  ('canon','history.event.cassian_valerian_death.612','death','Death of Cassian Valerian','year',612,null,null,null,null,'region.asteria','Lucan VII''s firstborn Cassian died at sea without issue in 612 CR.','canonical','authored',100,null,'0.6B',null),
  ('canon','history.event.julian_becomes_heir.612','other','Julian Valerian becomes current heir','year',612,null,null,null,null,'region.asteria','Cassian''s death without issue made Julian Valerian the current military heir.','canonical','authored',100,null,'0.6B',null),
  ('canon','history.event.mara_voss_election.623','election','Mara Voss elected High Captain','year',623,null,null,null,null,'origin.blackhaven','Mara Voss won the Blackhaven High Captain election through alliances, profitable raids, reputation, crew loyalty, and a coalition of rivals who preferred her to one another.','canonical','authored',100,null,'0.6B',null)
on conflict (world_scope_id,id) do nothing;

insert into public.historical_event_participants (world_scope_id,event_id,character_id)
values
  ('canon','history.event.ashar_conversion.503','character.ashar_i_asharan'),
  ('canon','history.event.ashar_kingship.508','character.ashar_i_asharan'),
  ('canon','history.event.cassian_valerian_death.612','character.cassian_valerian'),
  ('canon','history.event.julian_becomes_heir.612','character.julian_valerian'),
  ('canon','history.event.mara_voss_election.623','character.mara_voss')
on conflict do nothing;

insert into public.historical_event_factions (world_scope_id,event_id,faction_id)
values
  ('canon','history.event.ashar_conversion.503','house.asharan'),
  ('canon','history.event.ashar_kingship.508','house.asharan'),
  ('canon','history.event.cassian_valerian_death.612','house.valerian'),
  ('canon','history.event.julian_becomes_heir.612','house.valerian')
on conflict do nothing;

insert into public.historical_event_links (world_scope_id,id,source_event_id,target_event_id,relation_type,notes,canonical_status,origin)
values
  ('canon','history.link.ashar_conversion_to_kingship','history.event.ashar_conversion.503','history.event.ashar_kingship.508','contributed_to','Ashar''s sincere conversion also strengthened a political program that later shaped Asharan legitimacy.','canonical','authored'),
  ('canon','history.link.cassian_death_to_julian_heir','history.event.cassian_valerian_death.612','history.event.julian_becomes_heir.612','enabled','The firstborn''s death without issue shifted the active Valerian succession position to Julian.','canonical','authored')
on conflict (world_scope_id,id) do nothing;

set constraints all immediate;
commit;

-- No save-schema bump in 0.6B: this pass expands canonical persistent world-history data only.
